const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const scoreEl=document.getElementById('score'),bestEl=document.getElementById('best'),overlay=document.getElementById('overlay'),title=document.getElementById('overlayTitle'),text=document.getElementById('overlayText'),startBtn=document.getElementById('startBtn');
const W=canvas.width,H=canvas.height,GROUND=72;
let state='ready',score=0,best=Number(localStorage.getItem('floppyBest')||0),last=0,spawn=0,pipes=[];
bestEl.textContent=best;
const bird={x:105,y:300,r:17,vy:0,rot:0};
const cfg={gravity:1450,flap:-440,pipeSpeed:165,pipeWidth:68,gap:168,spawnEvery:1.45};
function reset(){score=0;scoreEl.textContent=0;pipes=[];spawn=.8;bird.y=H*.42;bird.vy=0;bird.rot=0;state='playing';overlay.classList.add('hidden');last=performance.now();}
function flap(){if(state==='ready'||state==='dead'){reset();bird.vy=cfg.flap;return}if(state==='playing')bird.vy=cfg.flap;}
function gameOver(){if(state!=='playing')return;state='dead';best=Math.max(best,score);localStorage.setItem('floppyBest',best);bestEl.textContent=best;title.textContent='Game Over';text.textContent=`Score: ${score} · Best: ${best}. Ready for another flight?`;startBtn.textContent='Play Again';overlay.classList.remove('hidden');}
function addPipe(){const margin=95,min=margin,max=H-GROUND-margin-cfg.gap;const top=Math.random()*(max-min)+min;pipes.push({x:W+20,top,passed:false});}
function update(dt){if(state!=='playing')return;bird.vy+=cfg.gravity*dt;bird.y+=bird.vy*dt;bird.rot=Math.max(-.45,Math.min(1.25,bird.vy/650));spawn-=dt;if(spawn<=0){addPipe();spawn=cfg.spawnEvery}for(const p of pipes){p.x-=cfg.pipeSpeed*dt;if(!p.passed&&p.x+cfg.pipeWidth<bird.x){p.passed=true;score++;scoreEl.textContent=score}}pipes=pipes.filter(p=>p.x>-cfg.pipeWidth-5);if(bird.y-bird.r<0||bird.y+bird.r>H-GROUND)return gameOver();for(const p of pipes){const hitX=bird.x+bird.r>p.x&&bird.x-bird.r<p.x+cfg.pipeWidth;const hitY=bird.y-bird.r<p.top||bird.y+bird.r>p.top+cfg.gap;if(hitX&&hitY)return gameOver();}}
function roundedRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function drawBackground(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#6dd5fa');g.addColorStop(1,'#d7f5ff');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffffff88';for(let i=0;i<5;i++){const x=(i*103+35)%W,y=75+(i%3)*75;ctx.beginPath();ctx.arc(x,y,22,0,Math.PI*2);ctx.arc(x+24,y+5,17,0,Math.PI*2);ctx.arc(x-22,y+8,14,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#86c85b';ctx.fillRect(0,H-GROUND,W,GROUND);ctx.fillStyle='#5aa33d';ctx.fillRect(0,H-GROUND,W,8);ctx.fillStyle='#78bb4d';for(let x=0;x<W;x+=24)ctx.fillRect(x,H-GROUND+17,12,5)}
function drawPipes(){for(const p of pipes){ctx.fillStyle='#43a047';roundedRect(p.x,-15,cfg.pipeWidth,p.top+15,8);roundedRect(p.x,p.top+cfg.gap,cfg.pipeWidth,H-(p.top+cfg.gap)-GROUND+15,8);ctx.fillStyle='#66bb4f';ctx.fillRect(p.x+8,0,11,p.top);ctx.fillRect(p.x+8,p.top+cfg.gap,11,H-p.top-cfg.gap-GROUND);ctx.fillStyle='#2e7d32';ctx.fillRect(p.x+cfg.pipeWidth-9,0,7,p.top);ctx.fillRect(p.x+cfg.pipeWidth-9,p.top+cfg.gap,7,H-p.top-cfg.gap-GROUND)}}
function drawBird(){ctx.save();ctx.translate(bird.x,bird.y);ctx.rotate(bird.rot);ctx.fillStyle='#facc15';ctx.beginPath();ctx.ellipse(0,0,22,17,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f59e0b';ctx.beginPath();ctx.ellipse(-11,5,13,8,-.35,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(10,-6,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111827';ctx.beginPath();ctx.arc(12,-6,3,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fb923c';ctx.beginPath();ctx.moveTo(19,-1);ctx.lineTo(34,4);ctx.lineTo(19,8);ctx.closePath();ctx.fill();ctx.restore()}
function draw(){drawBackground();drawPipes();drawBird();if(state==='playing'){ctx.font='900 46px system-ui';ctx.textAlign='center';ctx.lineWidth=6;ctx.strokeStyle='#0006';ctx.strokeText(score,W/2,70);ctx.fillStyle='#fff';ctx.fillText(score,W/2,70)}}
function loop(now){const dt=Math.min((now-last)/1000,.033)||0;last=now;update(dt);draw();requestAnimationFrame(loop)}
function togglePause(){if(state==='playing'){state='paused';title.textContent='Paused';text.textContent='Press P or tap Resume to continue.';startBtn.textContent='Resume';overlay.classList.remove('hidden')}else if(state==='paused'){state='playing';overlay.classList.add('hidden');last=performance.now()}}
startBtn.addEventListener('click',e=>{e.stopPropagation();state==='paused'?togglePause():reset()});canvas.addEventListener('pointerdown',flap);window.addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();flap()}if(e.key.toLowerCase()==='p')togglePause()});
requestAnimationFrame(loop);